name: Spot Free Floor Care
favicon: null
layout_spectrum: 0.3054716393817216
typography_spectrum: 0.5735665133688599
title: Spot Free Floor Care
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#464443'
    - '#0054d4'
    - '#030303'
    - '#ead7c3'
  brandStrength: 0.4181069831829518
  lightness: 0.6104057708289474
  saturation: 0.5790556885767728
  rhythmicContrast: 0.26864552148617804
purpose: []
